### ISSUE TITLE
Not importing on Ubuntu docker image

### ISSUE THREAD

**Issue by genotrance** [karpierz/libcurl#1]
Just installed libcurl-ct on an Ubuntu docker. Python 3.8, libcurl-ct installed using pip.

```python
# python3
Python 3.8.10 (default, Mar 15 2022, 12:22:08)
[GCC 9.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import libcurl
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.8/dist-packages/libcurl/__init__.py", line 9, in <module>
    from ._curl import *  # noqa
  File "/usr/local/lib/python3.8/dist-packages/libcurl/_curl.py", line 32, in <module>
    from ._platform import CFUNC, defined, from_oid
  File "/usr/local/lib/python3.8/dist-packages/libcurl/_platform/__init__.py", line 36, in <module>
    from ._windows import time_t
  File "/usr/local/lib/python3.8/dist-packages/libcurl/_platform/_windows/__init__.py", line 24, in <module>
    from ctypes  import WinDLL as DLL
ImportError: cannot import name 'WinDLL' from 'ctypes' (/usr/lib/python3.8/ctypes/__init__.py)
```

For some reason, it thinks this is Windows on import. However:

```python
>>> import platform
>>> import sys
>>> import os
>>> is_windows = (bool(platform.win32_ver()[0]) or
...               (sys.platform in ("win32", "cygwin")) or
...               (sys.platform == "cli" and os.name in ("nt", "ce")) or
...               (os.name == "java" and
...                "windows" in platform.java_ver()[3][0].lower()))
>>> is_windows
False
```

**Comment by genotrance** [comment]
I tried this on an Alpine system (#2 after removing py3-pip and manually installing pip, etc.) and can duplicate this there as well.

```python
# python3
Python 3.9.7 (default, Nov 24 2021, 21:15:59)
[GCC 10.3.1 20211027] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import libcurl
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.9/site-packages/libcurl/__init__.py", line 9, in <module>
    from ._curl import *  # noqa
  File "/usr/lib/python3.9/site-packages/libcurl/_curl.py", line 32, in <module>
    from ._platform import CFUNC, defined, from_oid
  File "/usr/lib/python3.9/site-packages/libcurl/_platform/__init__.py", line 36, in <module>
    from ._windows import time_t
  File "/usr/lib/python3.9/site-packages/libcurl/_platform/_windows/__init__.py", line 24, in <module>
    from ctypes  import WinDLL as DLL
ImportError: cannot import name 'WinDLL' from 'ctypes' (/usr/lib/python3.9/ctypes/__init__.py)
```

```python
>>> import platform
>>> import os
>>> import sys
>>> is_windows = (bool(platform.win32_ver()[0]) or
...               (sys.platform in ("win32", "cygwin")) or
...               (sys.platform == "cli" and os.name in ("nt", "ce")) or
...               (os.name == "java" and
...                "windows" in platform.java_ver()[3][0].lower()))
>>> is_windows
False
```
